[versions]
compileSdk = "36"
minSdk = "27"
targetSdk = "36"
versionCode = "1"
versionName = "1.0.0"

# Build Tools
agp = "8.13.2"

# AndroidX
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.9.4"
datastorePreferences = "1.1.7"
androidxAppCompat = "1.7.1"

# Compose
activityCompose = "1.11.0"
composeBom = "2025.10.01"
navigationCompose = "2.9.5"

# Kotlin
kotlin = "2.2.21"
kotlinxImmutable = "0.4.0"
kotlinxSerializationJson = "1.9.0"
kotlinParcelize = "2.2.21"

## Kotlin Symbol Processing
ksp = "2.2.21-2.0.4"

# Test
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

# Third Party
lottieCompose = "6.6.6"
coil = "3.3.0"
ktlint = "11.5.1"

# Network
okhttp = "5.1.0"
retrofit = "3.0.0"
retrofitKotlinSerializationConverter = "1.0.0"

# DI
hilt = "2.57.1"
hiltNavigationCompose = "1.2.0"

# Logging
timber = "5.0.1"

[libraries]
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Third Party
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieCompose" }

# Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

# Network
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinSerializationConverter" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# DI
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Logging
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[bundles]
androidx-core = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "androidx-appcompat",
    "androidx-material3",
]

compose = [
    "androidx-activity-compose",
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
    "androidx-compose-navigation",
]

network = [
    "retrofit-core",
    "retrofit-kotlin-serialization",
    "okhttp-logging",
]

hilt = [
    "hilt-android",
    "hilt-navigation-compose",
]

debug = [
    "androidx-ui-tooling",
    "androidx-ui-test-manifest"
]

test = [
    "androidx-junit",
    "androidx-ui-test-junit4",
    "androidx-espresso-core",
]